import importAll from 'import-all.macro';
const urls = importAll.sync('./music/**');

export const customSongs = [
    {
        title: "Bonetrousle",
        artist: "Cover by D-Man",
        instruments: [0x05, 0x54],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Battle Against a Funky Foe",
        artist: "D-Man",
        instruments: [0x05, 0x4a],
    },
    {
        title: "Song 48",
        artist: "D-Man",
        instruments: [0x05, 0x59],
    },
    {
        title: "Song 47",
        artist: "D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Song 40",
        artist: "D-Man",
        instruments: [0x05, 0x21],
    },
    {
        title: "Song 39",
        artist: "D-Man",
        instruments: [0x05, 0x21],
    },
    {
        title: "Song 38",
        artist: "D-Man",
        instruments: [0x05, 0x7c],
    },
    {
        title: "Song 36",
        artist: "D-Man",
        instruments: [0x05, 0x40],
    },
    {
        title: "Song 34",
        artist: "D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Song 33",
        artist: "D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Song 32",
        artist: "D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Song 31",
        artist: "D-Man",
        instruments: [0x05, 0x08],
    },
    {
        title: "Song 26",
        artist: "D-Man",
        instruments: [0x05, 0x34],
    },
    {
        title: "Town6",
        artist: "D-Man",
        instruments: [0x05, 0x2F],
    },
    {
        title: "Song 24",
        artist: "D-Man",
        instruments: [0x05, 0x54],
    },
    {
        title: "Song 22",
        artist: "D-Man",
        instruments: [0x05, 0x40],
    },
    {
        title: "Dark Bowser",
        artist: "Cover by D-Man",
        instruments: [0x05, 0x40],
    },
    {
        title: "Song 21",
        artist: "D-Man",
        instruments: [0x05, 0x34],
    },
    {
        title: "Song 20",
        artist: "D-Man",
        instruments: [0x05, 0x34],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Song 19",
        artist: "D-Man",
        instruments: [0x05, 0x40],
    },
    {
        title: "Home Guitar Version",
        artist: "Cover by D-Man",
        instruments: [0x05, 0x34],
    },
    {
        title: "Home Music Box Version",
        artist: "Cover by D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Town4",
        artist: "D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Town4s Night",
        artist: "D-Man",
        instruments: [0x05, 0x18],
    },
    {
        title: "Bacon Flavored",
        artist: "Cover by vince94",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Battle with a Dangerous Foe",
        artist: "vince94",
        instruments: [0x05, 0x54],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Battle With a Flippant Foe",
        artist: "vince94",
        instruments: [0x05, 0x76],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Brinstar Red Soil",
        artist: "Cover by vince94",
        instruments: [0x05, 0x32],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Beginning",
        artist: "Cover by vince94",
        instruments: [0x05, 0x32],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Susie",
        artist: "Cover by vince94",
        instruments: [0x05, 0x32],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Friendliness",
        artist: "Cover by vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Megalovania",
        artist: "Cover by vince94",
        instruments: [0x05, 0x7c],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Moonsong",
        artist: "Cover by vince94",
        instruments: [0x05, 0x23],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Ruins",
        artist: "Cover by vince94",
        instruments: [0x05, 0x15],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Summers Plaza",
        artist: "Cover by vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "The Battle of Lil Slugger",
        artist: "Cover by vince94",
        instruments: [0x05, 0x7A],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "The High Sign",
        artist: "vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Time Trax Music 02",
        artist: "Cover by vince94",
        instruments: [0x05, 0x7C],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Casino Night Zone",
        artist: "Cover by vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Grandiose Foe",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Akira Volume",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x54],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "SMT Chaos",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "SMT Nocturne Fierce Battle",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x7c],
        isOverworld: false,
        isBattle: false,
        isBoss: true,
    },
    {
        title: "SMT II Chaos",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x40],
        isOverworld: false,
        isBattle: false,
        isBoss: true,
    },
    {
        title: "SMT II 3D Valhalla",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x6e],
        isOverworld: false,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "I'll Face Myself",
        filename: "I_ll_Face_Myself",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x7c],
        isOverworld: false,
        isBattle: false,
        isBoss: true,
    },
    {
        title: "Kazuya Volume",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x7c],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Say Face D-Mix",
        artist: "Ari3s and D-Man",
        instruments: [0x05, 0x08],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Battle with Magus",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x40],
        isOverworld: false,
        isBattle: false,
        isBoss: true,
    },
    {
        title: "Battle Against a Gatekeeper",
        artist: "Ari3s",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Requiem for the Champions",
        artist: "Ari3s",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Terminal Velocity",
        artist: "Ari3s",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Friendly Neighbors Reggae",
        artist: "vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Hospital Dr Dick",
        artist: "Blazephlozard",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Home Sweet Family Guy",
        artist: "vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Faron Woods",
        artist: "Cover by vince94",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Our House",
        artist: "Blazephlozard",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Save the Leekspin",
        artist: "Xarlable",
        instruments: [0x05, 0x15],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Magicalphys",
        artist: "Blazephlozard",
        instruments: [0x05, 0x18],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Summers Girls",
        artist: "Blazephlozard",
        instruments: [0x05, 0x32],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Mobile Flinstones",
        artist: "Xarlable",
        instruments: [0x05, 0x6E],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Johnny B Goode",
        artist: "Triple-Q",
        instruments: [0x05, 0x74],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Megalokrakia",
        artist: "avolience",
        instruments: [0x05, 0x7A],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Machine Gravity",
        artist: "Cover by Blazephlozard",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Masked Man Strong One",
        artist: "Cover by Blazephlozard",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Techno Boss Battle Mettaton",
        artist: "Blazephlozard",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Geothermal",
        artist: "Cover by Blazephlozard",
        instruments: [0x05, 0x7C],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Knights of Cydonia",
        artist: "Cover by Blazephlozard",
        instruments: [0x05, 0x7C],
        isOverworld: false,
        isBattle: false,
        isBoss: true,
    },
    {
        title: "What is Love",
        artist: "Cover by Blazephlozard",
        instruments: [0x05, 0x8B],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Welcome Booster",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x36],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Human Music",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x2A],
        isOverworld: false,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Pursuit Cornered",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x54],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Tetrinet",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Kraid Lair",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Dragon Warrior Overworld",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Mii Channel",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Wily Castle v3",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Waterworld Map",
        artist: "Cover by Aurilliux",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Sand Hut",
        artist: "EBisumaru",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "Forest Themest",
        artist: "EBisumaru",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: true,
        isBoss: false,
    },
    {
        title: "A Bad Dream",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: true,
    },
    {
        title: "Chiaki",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Crossing Over",
        artist: "Ari3s",
        instruments: [0x05, 0x08],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Never Ending Journey",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x2F],
        isOverworld: true,
        isBattle: false,
        isBoss: false,
    },
    {
        title: "Poltergeist",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x54],
        isOverworld: true,
        isBattle: true,
        isBoss: true,
    },
    {
        title: "Suspense",
        artist: "Cover by Ari3s",
        instruments: [0x05, 0x40],
        isOverworld: true,
        isBattle: false,
        isBoss: true,
    },
];

export async function prepareCustomSongIndex(index) {
    if(index >= customSongs.length) {
        throw new Error(`Invalid custom song index.`);
    }
    const song = customSongs[index];
    return await prepareCustomSong(song);
}

export async function prepareCustomSong(song) {
    let url = urls[`./music/${song.filename || song.title.replace(/ /g, '_')}.ebm.bin`];
    if(!url) {
        url = urls[`./music/${song.title}.ebm.bin`];
    }
    if(!url) {
        throw new Error(`Could not find music ebm file for ${song.title}.`);
    }
    let response = await fetch(url);
    let buffer = await response.arrayBuffer();
    let data = new Uint8Array(buffer);

    if(data.length < 4) {
        throw new Error(`Invalid song data length.`);
    }
    const songAddress = data.slice(2, 4);
    return Object.assign({ data, songAddress }, song);
}